# Lab 2.1 - Sync provider secret into Kubernetes Secret db-secret.
# For local fallback, change secretStoreRef.name to fake-secrets and add version: v1/v2.
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-secret
  namespace: demo
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: db-secret
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: /demo/db/password
